export default [
	{
		title: 'Action (set A)',
		img: '/assets/img/dance.jpg',
		id: 1,
		words: [
			{
				word: 'cry',
				translation: 'плакать',
				img: '/assets/img/cry.jpg',
				audioSrc: '/assets/audio/cry.mp3',
				id: 1,
			},
			{
				word: 'dance',
				translation: 'танцевать',
				img: '/assets/img/dance.jpg',
				audioSrc: '/assets/audio/dance.mp3',
				id: 2,
			},
			{
				word: 'dive',
				translation: 'нырять',
				img: '/assets/img/dive.jpg',
				audioSrc: '/assets/audio/dive.mp3',
				id: 3,
			},
			{
				word: 'draw',
				translation: 'рисовать',
				img: '/assets/img/draw.jpg',
				audioSrc: '/assets/audio/draw.mp3',
				id: 4,
			},
			{
				word: 'fish',
				translation: 'ловить рыбу',
				img: '/assets/img/fish.jpg',
				audioSrc: '/assets/audio/fish.mp3',
				id: 5,
			},
			{
				word: 'fly',
				translation: 'летать',
				img: '/assets/img/fly.jpg',
				audioSrc: '/assets/audio/fly.mp3',
				id: 6,
			},
			{
				word: 'hug',
				translation: 'обнимать',
				img: '/assets/img/hug.jpg',
				audioSrc: '/assets/audio/hug.mp3',
				id: 7,
			},
			{
				word: 'jump',
				translation: 'прыгать',
				img: '/assets/img/jump.jpg',
				audioSrc: '/assets/audio/jump.mp3',
				id: 8,
			},
		],
	},
	{
		title: 'Action (set B)',
		img: '/assets/img/swim.jpg',
		id: 2,
		words: [
			{
				word: 'open',
				translation: 'открывать',
				img: '/assets/img/open.jpg',
				audioSrc: '/assets/audio/open.mp3',
				id: 9,
			},
			{
				word: 'play',
				translation: 'играть',
				img: '/assets/img/play.jpg',
				audioSrc: '/assets/audio/play.mp3',
				id: 10,
			},
			{
				word: 'point',
				translation: 'указывать',
				img: '/assets/img/point.jpg',
				audioSrc: '/assets/audio/point.mp3',
				id: 11,
			},
			{
				word: 'ride',
				translation: 'ездить',
				img: '/assets/img/ride.jpg',
				audioSrc: '/assets/audio/ride.mp3',
				id: 12,
			},
			{
				word: 'run',
				translation: 'бегать',
				img: '/assets/img/run.jpg',
				audioSrc: '/assets/audio/run.mp3',
				id: 13,
			},
			{
				word: 'sing',
				translation: 'петь',
				img: '/assets/img/sing.jpg',
				audioSrc: '/assets/audio/sing.mp3',
				id: 14,
			},
			{
				word: 'skip',
				translation: 'пропускать, прыгать',
				img: '/assets/img/skip.jpg',
				audioSrc: '/assets/audio/skip.mp3',
				id: 15,
			},
			{
				word: 'swim',
				translation: 'плавать',
				img: '/assets/img/swim.jpg',
				audioSrc: '/assets/audio/swim.mp3',
				id: 16,
			},
		],
	},
	{
		title: 'Action (set C)',
		img: '/assets/img/read.jpg',
		id: 3,
		words: [
			{
				word: 'read',
				translation: 'читать',
				img: '/assets/img/read.jpg',
				audioSrc: '/assets/audio/read.mp3',
				id: 17,
			},
			{
				word: 'sleep',
				translation: 'спать',
				img: '/assets/img/sleep.jpg',
				audioSrc: '/assets/audio/sleep.mp3',
				id: 18,
			},
			{
				word: 'study',
				translation: 'учиться',
				img: '/assets/img/study.jpg',
				audioSrc: '/assets/audio/study.mp3',
				id: 19,
			},
			{
				word: 'help',
				translation: 'помогать',
				img: '/assets/img/help.jpg',
				audioSrc: '/assets/audio/help.mp3',
				id: 20,
			},
			{
				word: 'cook',
				translation: 'готовить',
				img: '/assets/img/cook.jpg',
				audioSrc: '/assets/audio/cook.mp3',
				id: 22,
			},
			{
				word: 'drink',
				translation: 'пить',
				img: '/assets/img/drink.jpg',
				audioSrc: '/assets/audio/drink.mp3',
				id: 23,
			},
			{
				word: 'listen',
				translation: 'слушать',
				img: '/assets/img/listen.jpg',
				audioSrc: '/assets/audio/listen.mp3',
				id: 24,
			},
			{
				word: 'eat',
				translation: 'кушать',
				img: '/assets/img/eat.jpg',
				audioSrc: '/assets/audio/eat.mp3',
				id: 25,
			},
		],
	},
	{
		title: 'Abjective',
		img: '/assets/img/funny.jpg',
		id: 4,
		words: [
			{
				word: 'beautiful',
				translation: 'красивый',
				img: '/assets/img/beautiful.jpg',
				audioSrc: '/assets/audio/beautiful.mp3',
				id: 26,
			},
			{
				word: 'big',
				translation: 'большой',
				img: '/assets/img/big.jpg',
				audioSrc: '/assets/audio/big.mp3',
				id: 27,
			},
			{
				word: 'tasty',
				translation: 'вкусный',
				img: '/assets/img/tasty.jpg',
				audioSrc: '/assets/audio/tasty.mp3',
				id: 28,
			},
			{
				word: 'old',
				translation: 'старый',
				img: '/assets/img/old.jpg',
				audioSrc: '/assets/audio/old.mp3',
				id: 29,
			},
			{
				word: 'friendly',
				translation: 'дружелюбный',
				img: '/assets/img/friendly.jpg',
				audioSrc: '/assets/audio/friendly.mp3',
				id: 30,
			},
			{
				word: 'funny',
				translation: 'смешной',
				img: '/assets/img/funny.jpg',
				audioSrc: '/assets/audio/funny.mp3',
				id: 31,
			},
			{
				word: 'colorful',
				translation: 'разноцветный',
				img: '/assets/img/colorful.jpg',
				audioSrc: '/assets/audio/colorful.mp3',
				id: 32,
			},
			{
				word: 'small',
				translation: 'маленький',
				img: '/assets/img/small.jpg',
				audioSrc: '/assets/audio/small.mp3',
				id: 33,
			},
		],
	},
	{
		title: 'Animal (set A)',
		img: '/assets/img/rabbit.jpg',
		id: 5,
		words: [
			{
				word: 'cat',
				translation: 'кот',
				img: '/assets/img/cat.jpg',
				audioSrc: '/assets/audio/cat.mp3',
				id: 34,
			},
			{
				word: 'chick',
				translation: 'цыплёнок',
				img: '/assets/img/chick.jpg',
				audioSrc: '/assets/audio/chick.mp3',
				id: 35,
			},
			{
				word: 'chicken',
				translation: 'курица',
				img: '/assets/img/chicken.jpg',
				audioSrc: '/assets/audio/chicken.mp3',
				id: 36,
			},
			{
				word: 'dog',
				translation: 'собака',
				img: '/assets/img/dog.jpg',
				audioSrc: '/assets/audio/dog.mp3',
				id: 37,
			},
			{
				word: 'horse',
				translation: 'лошадь',
				img: '/assets/img/horse.jpg',
				audioSrc: '/assets/audio/horse.mp3',
				id: 38,
			},
			{
				word: 'pig',
				translation: 'свинья',
				img: '/assets/img/pig.jpg',
				audioSrc: '/assets/audio/pig.mp3',
				id: 39,
			},
			{
				word: 'rabbit',
				translation: 'кролик',
				img: '/assets/img/rabbit.jpg',
				audioSrc: '/assets/audio/rabbit.mp3',
				id: 40,
			},
			{
				word: 'sheep',
				translation: 'овца',
				img: '/assets/img/sheep.jpg',
				audioSrc: '/assets/audio/sheep.mp3',
				id: 41,
			},
		],
	},
	{
		title: 'Animal (set B)',
		img: '/assets/img/lion.jpg',
		id: 6,
		words: [
			{
				word: 'bird',
				translation: 'птица',
				img: '/assets/img/bird.jpg',
				audioSrc: '/assets/audio/bird.mp3',
				id: 42,
			},
			{
				word: 'fish',
				translation: 'рыба',
				img: '/assets/img/fish1.jpg',
				audioSrc: '/assets/audio/fish.mp3',
				id: 43,
			},
			{
				word: 'frog',
				translation: 'жаба',
				img: '/assets/img/frog.jpg',
				audioSrc: '/assets/audio/frog.mp3',
				id: 44,
			},
			{
				word: 'giraffe',
				translation: 'жирафа',
				img: '/assets/img/giraffe.jpg',
				audioSrc: '/assets/audio/giraffe.mp3',
				id: 45,
			},
			{
				word: 'lion',
				translation: 'лев',
				img: '/assets/img/lion.jpg',
				audioSrc: '/assets/audio/lion.mp3',
				id: 46,
			},
			{
				word: 'mouse',
				translation: 'мышь',
				img: '/assets/img/mouse.jpg',
				audioSrc: '/assets/audio/mouse.mp3',
				id: 47,
			},
			{
				word: 'turtle',
				translation: 'черепаха',
				img: '/assets/img/turtle.jpg',
				audioSrc: '/assets/audio/turtle.mp3',
				id: 48,
			},
			{
				word: 'dolphin',
				translation: 'дельфин',
				img: '/assets/img/dolphin.jpg',
				audioSrc: '/assets/audio/dolphin.mp3',
				id: 49,
			},
		],
	},
	{
		title: 'Clothes',
		img: '/assets/img/dress.jpg',
		id: 7,
		words: [
			{
				word: 'skirt',
				translation: 'юбка',
				img: '/assets/img/skirt.jpg',
				audioSrc: '/assets/audio/skirt.mp3',
				id: 50,
			},
			{
				word: 'pants',
				translation: 'брюки',
				img: '/assets/img/pants.jpg',
				audioSrc: '/assets/audio/pants.mp3',
				id: 51,
			},
			{
				word: 'blouse',
				translation: 'блузка',
				img: '/assets/img/blouse.jpg',
				audioSrc: '/assets/audio/blouse.mp3',
				id: 52,
			},
			{
				word: 'dress',
				translation: 'платье',
				img: '/assets/img/dress.jpg',
				audioSrc: '/assets/audio/dress.mp3',
				id: 53,
			},
			{
				word: 'boot',
				translation: 'ботинок',
				img: '/assets/img/boot.jpg',
				audioSrc: '/assets/audio/boot.mp3',
				id: 54,
			},
			{
				word: 'shirt',
				translation: 'рубашка',
				img: '/assets/img/shirt.jpg',
				audioSrc: '/assets/audio/shirt.mp3',
				id: 55,
			},
			{
				word: 'coat',
				translation: 'пальто',
				img: '/assets/img/coat.jpg',
				audioSrc: '/assets/audio/coat.mp3',
				id: 56,
			},
			{
				word: 'shoe',
				translation: 'туфли',
				img: '/assets/img/shoe.jpg',
				audioSrc: '/assets/audio/shoe.mp3',
				id: 57,
			},
		],
	},
	{
		title: 'Emotions',
		img: '/assets/img/smile.jpg',
		id: 8,
		words: [
			{
				word: 'sad',
				translation: 'грустный',
				img: '/assets/img/sad.jpg',
				audioSrc: '/assets/audio/sad.mp3',
				id: 58,
			},
			{
				word: 'angry',
				translation: 'сердитый',
				img: '/assets/img/angry.jpg',
				audioSrc: '/assets/audio/angry.mp3',
				id: 59,
			},
			{
				word: 'happy',
				translation: 'счастливый',
				img: '/assets/img/happy.jpg',
				audioSrc: '/assets/audio/happy.mp3',
				id: 60,
			},
			{
				word: 'tired',
				translation: 'уставший',
				img: '/assets/img/tired.jpg',
				audioSrc: '/assets/audio/tired.mp3',
				id: 61,
			},
			{
				word: 'surprised',
				translation: 'удивлённый',
				img: '/assets/img/surprised.jpg',
				audioSrc: '/assets/audio/surprised.mp3',
				id: 62,
			},
			{
				word: 'scared',
				translation: 'испуганный',
				img: '/assets/img/scared.jpg',
				audioSrc: '/assets/audio/scared.mp3',
				id: 63,
			},
			{
				word: 'smile',
				translation: 'улыбка',
				img: '/assets/img/smile.jpg',
				audioSrc: '/assets/audio/smile.mp3',
				id: 64,
			},
			{
				word: 'laugh',
				translation: 'смех',
				img: '/assets/img/laugh.jpg',
				audioSrc: '/assets/audio/laugh.mp3',
				id: 65,
			},
		],
	},
];
